src/main/java/org/test/teamproject_back/controller/AdminController.java, src/main/java/org/test/teamproject_back/entity/UserRoles.java, src/main/java/org/test/teamproject_back/init/AdminDataInit.java, src/main/java/org/test/teamproject_back/repository/AdminMapper.java, src/main/java/org/test/teamproject_back/service/AdminService.java, src/main/resources/mappers/admin.xml
=> 관리자 로그인 만드는 중

src/main/java/org/test/teamproject_back/controller/ProductController.java, src/main/java/org/test/teamproject_back/dto/request/ReqAddProductDto.java, src/main/java/org/test/teamproject_back/entity/Product.java, src/main/java/org/test/teamproject_back/repository/ProductMapper.java, src/main/java/org/test/teamproject_back/service/ProductService.java, src/main/resources/mappers/product.xml
- addProduct 메소드 작성(상품추가)
- Post 요청으로 받음
- 받은 내용을 Product 형태로 바꾸어 ProductMapper 호출
- 받은 Product를 product.xml을 통해서 데이터베이스에 insert
=> 상품 등록 기능 추가

src/main/java/org/test/teamproject_back/controller/AdminController.java, src/main/java/org/test/teamproject_back/controller/ProductController.java, src/main/java/org/test/teamproject_back/dto/request/ReqAddProductDto.java, src/main/java/org/test/teamproject_back/service/ProductService.java, src/main/resources/application.yml
=> 관리자 페이지 연결 점검 및 수정

src/main/java/org/test/teamproject_back/controller/CartController.java, src/main/java/org/test/teamproject_back/entity/Cart.java, src/main/java/org/test/teamproject_back/entity/CartItem.java, src/main/java/org/test/teamproject_back/service/UserService.java
=> 장바구니 기능 추가

src/main/java/org/test/teamproject_back/controller/CartController.java, src/main/java/org/test/teamproject_back/dto/request/ReqDeleteCartDto.java, src/main/java/org/test/teamproject_back/repository/CartItemMapper.java, src/main/java/org/test/teamproject_back/service/CartService.java, src/main/resources/mappers/cart_item.xml
=> 33 장바구니 기능 완료

src/main/java/org/test/teamproject_back/controller/ProductLikeController.java, src/main/java/org/test/teamproject_back/entity/ProductLike.java, src/main/java/org/test/teamproject_back/repository/ProductLikeMapper.java, src/main/java/org/test/teamproject_back/service/ProductLikeService.java, src/main/resources/mappers/product_like.xml
product like 기능 구현
- 찜 버튼 클릭 시 찜 등록되고 한번더 클릭시 해제
- 내 찜 목록 들어가면 자동으로 찜 한것들 출력
=> product like 기능 구현

src/main/java/org/test/teamproject_back/config/SecurityConfig.java, src/main/java/org/test/teamproject_back/controller/AddressController.java, src/main/java/org/test/teamproject_back/controller/AdminUserController.java, src/main/java/org/test/teamproject_back/controller/AuthController.java, src/main/java/org/test/teamproject_back/controller/CartController.java, src/main/java/org/test/teamproject_back/controller/EmailController.java, src/main/java/org/test/teamproject_back/controller/ProductController.java, src/main/java/org/test/teamproject_back/controller/ProductLikeController.java, src/main/java/org/test/teamproject_back/controller/UserController.java, src/main/java/org/test/teamproject_back/dto/request/ReqAddressDto.java, src/main/java/org/test/teamproject_back/dto/request/ReqModifyAdminUserDto.java, src/main/java/org/test/teamproject_back/dto/request/ReqModifyUserDto.java, src/main/java/org/test/teamproject_back/dto/response/RespProductDetailDto.java, src/main/java/org/test/teamproject_back/entity/Address.java, src/main/java/org/test/teamproject_back/repository/AddressMapper.java, src/main/java/org/test/teamproject_back/repository/ProductMapper.java, src/main/java/org/test/teamproject_back/repository/UserMapper.java, src/main/java/org/test/teamproject_back/service/AdminUserService.java, src/main/java/org/test/teamproject_back/service/ProductService.java, src/main/java/org/test/teamproject_back/service/UserService.java, src/main/resources/mappers/product.xml, src/main/resources/mappers/user.xml
=> url 변경, 유저 정보 조회 기능 추가

src/main/java/org/test/teamproject_back/controller/ProductController.java, src/main/java/org/test/teamproject_back/dto/response/RespGetProductDto.java, src/main/java/org/test/teamproject_back/repository/ProductMapper.java, src/main/java/org/test/teamproject_back/service/ProductService.java, src/main/resources/mappers/product.xml
=> 신상품, 인기상품 요청 받고 데이터 보내기

src/main/java/org/test/teamproject_back/controller/OrderController.java, src/main/java/org/test/teamproject_back/dto/response/RespCartOrderDto.java, src/main/java/org/test/teamproject_back/dto/response/RespUserInfoDto.java, src/main/java/org/test/teamproject_back/entity/Order.java, src/main/java/org/test/teamproject_back/repository/AddressMapper.java, src/main/java/org/test/teamproject_back/repository/CartItemMapper.java, src/main/java/org/test/teamproject_back/repository/CartMapper.java, src/main/java/org/test/teamproject_back/repository/OrderMapper.java, src/main/java/org/test/teamproject_back/service/CartService.java, src/main/java/org/test/teamproject_back/service/OrderService.java, src/main/java/org/test/teamproject_back/service/UserService.java, src/main/resources/mappers/address.xml, src/main/resources/mappers/cart.xml, src/main/resources/mappers/cart_item.xml, src/main/resources/mappers/order.xml
=> 주문 확인 페이지 기능 추가

src/main/java/org/test/teamproject_back/controller/ReviewController.java, src/main/java/org/test/teamproject_back/dto/request/ReqReviewDto.java, src/main/java/org/test/teamproject_back/entity/Review.java, src/main/java/org/test/teamproject_back/repository/ProductMapper.java, src/main/java/org/test/teamproject_back/repository/ReviewMapper.java, src/main/java/org/test/teamproject_back/repository/UserMapper.java, src/main/java/org/test/teamproject_back/service/ProductService.java, src/main/java/org/test/teamproject_back/service/ReviewService.java, src/main/resources/mappers/product.xml, src/main/resources/mappers/review.xml, src/main/resources/mappers/user.xml
=> 50 리뷰 등록 기능 추가

src/main/java/org/test/teamproject_back/controller/OrderController.java, src/main/java/org/test/teamproject_back/controller/ReviewController.java, src/main/java/org/test/teamproject_back/dto/request/ReqAddProductDto.java, src/main/java/org/test/teamproject_back/dto/request/ReqAddReviewDto.java, src/main/java/org/test/teamproject_back/dto/request/ReqCartListDto.java, src/main/java/org/test/teamproject_back/dto/request/ReqModifyProductDto.java, src/main/java/org/test/teamproject_back/dto/request/ReqModifyReviewDto.java, src/main/java/org/test/teamproject_back/entity/Product.java, src/main/java/org/test/teamproject_back/entity/Review.java, src/main/java/org/test/teamproject_back/repository/CartMapper.java, src/main/java/org/test/teamproject_back/repository/ReviewMapper.java, src/main/java/org/test/teamproject_back/service/OrderService.java, src/main/java/org/test/teamproject_back/service/ReviewService.java, src/main/resources/mappers/admin_product.xml, src/main/resources/mappers/cart.xml, src/main/resources/mappers/product.xml, src/main/resources/mappers/product_like.xml, src/main/resources/mappers/review.xml
=> 리뷰 기능, 쿼리 수정 중

src/main/java/org/test/teamproject_back/controller/ReviewController.java, src/main/java/org/test/teamproject_back/dto/request/ReqModifyReviewDto.java, src/main/java/org/test/teamproject_back/repository/ReviewMapper.java, src/main/java/org/test/teamproject_back/repository/UserMapper.java, src/main/java/org/test/teamproject_back/service/ProductService.java, src/main/java/org/test/teamproject_back/service/ReviewService.java, src/main/resources/mappers/admin_product.xml, src/main/resources/mappers/cart.xml, src/main/resources/mappers/product.xml, src/main/resources/mappers/review.xml, src/main/resources/mappers/user.xml
=> 리뷰 기능 수정 완료

pom.xml, src/main/java/org/test/teamproject_back/config/OAuth2Config.java, src/main/java/org/test/teamproject_back/config/SecurityConfig.java, src/main/java/org/test/teamproject_back/controller/AuthController.java, src/main/java/org/test/teamproject_back/controller/AuthenticationController.java, src/main/java/org/test/teamproject_back/dto/request/ReqOAuth2SignupDto.java, src/main/java/org/test/teamproject_back/entity/OAuth2User.java, src/main/java/org/test/teamproject_back/repository/OAuth2UserMapper.java, src/main/java/org/test/teamproject_back/security/handler/OAuth2SuccessHandler.java, src/main/java/org/test/teamproject_back/service/OAuth2Service.java, src/main/resources/mappers/oauth2_user.xml
=> oauth 인증 기능 생성중

src/main/java/org/test/teamproject_back/controller/AdminSalesController.java, src/main/java/org/test/teamproject_back/controller/OrderController.java, src/main/java/org/test/teamproject_back/dto/response/RespOrderDto.java, src/main/java/org/test/teamproject_back/dto/response/RespSalesDto.java, src/main/java/org/test/teamproject_back/entity/Order.java, src/main/java/org/test/teamproject_back/entity/Payment.java, src/main/java/org/test/teamproject_back/repository/OrderMapper.java, src/main/java/org/test/teamproject_back/repository/PaymentsMapper.java, src/main/java/org/test/teamproject_back/service/AdminSalesService.java, src/main/java/org/test/teamproject_back/service/OrderService.java, src/main/resources/mappers/order.xml, src/main/resources/mappers/payments.xml
=> 63 매출 관리 기능 추가

src/main/java/org/test/teamproject_back/controller/AdminProductController.java, src/main/java/org/test/teamproject_back/dto/request/ReqCartListDto.java, src/main/java/org/test/teamproject_back/service/OrderService.java, src/main/java/org/test/teamproject_back/service/ProductService.java
=> 결제 창 관련 오류 수정 중

src/main/java/org/test/teamproject_back/dto/response/RespSigninDto.java, src/main/java/org/test/teamproject_back/repository/RoleMapper.java, src/main/java/org/test/teamproject_back/repository/UserRolesMapper.java, src/main/java/org/test/teamproject_back/service/AuthService.java, src/main/java/org/test/teamproject_back/service/UserService.java, src/main/resources/mappers/role.xml
=> 관리자 로그인 수정

src/main/java/org/test/teamproject_back/controller/ProductController.java, src/main/java/org/test/teamproject_back/repository/ProductMapper.java, src/main/java/org/test/teamproject_back/service/ProductService.java, src/main/resources/mappers/product.xml
=> MD 추천 상품조회

src/main/java/org/test/teamproject_back/controller/UserController.java, src/main/java/org/test/teamproject_back/dto/response/RespUserInfoDto.java, src/main/java/org/test/teamproject_back/service/UserService.java
=> 75 마이 페이지 정보 조회 추가

src/main/java/org/test/teamproject_back/dto/response/RespUserInfoDto.java, src/main/java/org/test/teamproject_back/service/UserService.java
=> 마이페이지 유저 조회 수정

src/main/java/org/test/teamproject_back/controller/AdminProductController.java, src/main/java/org/test/teamproject_back/controller/ReviewController.java, src/main/java/org/test/teamproject_back/dto/request/ReqAddReviewDto.java, src/main/java/org/test/teamproject_back/dto/request/ReqDeleteReviewDto.java, src/main/java/org/test/teamproject_back/dto/request/ReqModifyReviewDto.java, src/main/java/org/test/teamproject_back/entity/Review.java, src/main/java/org/test/teamproject_back/repository/ReviewMapper.java, src/main/java/org/test/teamproject_back/service/ReviewService.java, src/main/resources/mappers/review.xml
=> 리뷰 조회 기능 수정

src/main/java/org/test/teamproject_back/service/UserService.java, src/main/resources/mappers/user.xml
=> 유저 정보 수정하기

src/main/java/org/test/teamproject_back/dto/request/ReqModifyUserDto.java, src/main/java/org/test/teamproject_back/service/UserService.java
=> 86 유저 정보 페이지 체크 비밀번호 확인 수정

src/main/java/org/test/teamproject_back/controller/AdminProductController.java, src/main/java/org/test/teamproject_back/dto/request/ReqAddProductDto.java, src/main/java/org/test/teamproject_back/dto/request/ReqModifyProductDto.java, src/main/java/org/test/teamproject_back/service/AdminProductService.java
=> 90 상품 수정 기능 변경 및 dto 수정

src/main/java/org/test/teamproject_back/controller/AuthController.java, src/main/java/org/test/teamproject_back/dto/request/ReqModifyUserDto.java, src/main/java/org/test/teamproject_back/service/UserService.java
=> 92 비밀번호 수정 완료

src/main/java/org/test/teamproject_back/controller/AdminProductController.java, src/main/java/org/test/teamproject_back/dto/request/ReqAddProductDto.java, src/main/java/org/test/teamproject_back/dto/request/ReqModifyProductDto.java, src/main/java/org/test/teamproject_back/service/AdminProductService.java
=> 94 add product dto 변수명 수정

src/main/java/org/test/teamproject_back/service/OAuth2Service.java
=> 104 oauth2 구글 로그인 및 회원가입

src/main/java/org/test/teamproject_back/controller/AdminProductController.java, src/main/java/org/test/teamproject_back/repository/ProductMapper.java, src/main/java/org/test/teamproject_back/service/ProductService.java, src/main/resources/mappers/product.xml
product 데이터 가져올 때 
20개, 11개, 19개 가져오는 오류가 있어
join 하는 부분에서 문제라 판단하여 group by 를 통해 product_id가 중복되지 않게 수정
이 후 20개, 20개, 10개 로 잘 나옴
=> product 데이터 select 수정

src/main/resources/mappers/review.xml
=> 115 리뷰 날짜 수정

src/main/java/org/test/teamproject_back/service/EmailService.java
=> 119 메일 인증 수정

src/main/java/org/test/teamproject_back/controller/OrderController.java, src/main/java/org/test/teamproject_back/dto/request/ReqCartListDto.java, src/main/java/org/test/teamproject_back/service/OrderService.java
=> 121 결제 페이지 주소 추가하기

src/main/java/org/test/teamproject_back/entity/Order.java, src/main/java/org/test/teamproject_back/service/OrderService.java, src/main/resources/mappers/admin_order.xml
=> 관리자 주문 관리 페이지 쿼리 수정

src/main/java/org/test/teamproject_back/controller/OrderController.java, src/main/java/org/test/teamproject_back/controller/PaymentController.java, src/main/java/org/test/teamproject_back/dto/request/ReqOrderDto.java, src/main/java/org/test/teamproject_back/entity/Payment.java, src/main/java/org/test/teamproject_back/repository/PaymentsMapper.java, src/main/java/org/test/teamproject_back/service/AdminSalesService.java, src/main/java/org/test/teamproject_back/service/PaymentService.java, src/main/resources/mappers/payments.xml
=> 결제 취소 로직 구현 중

src/main/java/org/test/teamproject_back/controller/UserController.java, src/main/java/org/test/teamproject_back/dto/request/ReqImgDto.java, src/main/java/org/test/teamproject_back/repository/UserMapper.java, src/main/java/org/test/teamproject_back/service/UserService.java, src/main/resources/mappers/user.xml
=> 이미지 프로필 수정

src/main/java/org/test/teamproject_back/controller/AuthController.java, src/main/java/org/test/teamproject_back/dto/request/ReqFindUsernameDto.java, src/main/java/org/test/teamproject_back/repository/UserMapper.java, src/main/java/org/test/teamproject_back/service/AuthService.java, src/main/resources/mappers/user.xml
=> 141 아이디 찾기 기능 추가

src/main/java/org/test/teamproject_back/controller/AuthController.java, src/main/java/org/test/teamproject_back/dto/request/ReqGeneratePasswordDto.java, src/main/java/org/test/teamproject_back/repository/UserMapper.java, src/main/java/org/test/teamproject_back/service/AuthService.java, src/main/resources/mappers/user.xml
=> 비밀번호 재생성 기능 추가

src/main/java/org/test/teamproject_back/controller/AdminUserController.java, src/main/java/org/test/teamproject_back/dto/request/ReqModifyAdminUserDto.java, src/main/java/org/test/teamproject_back/dto/request/ReqSearchUserDto.java, src/main/java/org/test/teamproject_back/repository/AdminUserMapper.java, src/main/java/org/test/teamproject_back/service/AdminUserService.java, src/main/resources/mappers/admin_user.xml
=> 유저 관리 페이지 수정 기능 완료

src/main/java/org/test/teamproject_back/controller/AdminProductController.java, src/main/java/org/test/teamproject_back/dto/request/ReqAddProductDto.java, src/main/java/org/test/teamproject_back/repository/PaymentsMapper.java, src/main/java/org/test/teamproject_back/repository/ProductMapper.java, src/main/java/org/test/teamproject_back/service/OrderService.java, src/main/java/org/test/teamproject_back/service/PaymentService.java, src/main/resources/mappers/payments.xml, src/main/resources/mappers/product.xml
=> 153 결제 취소 시 재고 업데이트 완료

src/main/resources/mappers/order.xml
=> 구매기록 정보 추가

src/main/java/org/test/teamproject_back/controller/OrderController.java, src/main/java/org/test/teamproject_back/dto/request/ReqProductOrderDto.java, src/main/java/org/test/teamproject_back/service/OrderService.java
=> 상품 결제 정보 불러오기
